from .user_routes import users
from .auth_routes import auth
from .course_routes import course
from .crystal_routes import crystal
from .enrollment_routes import enrollment
from .lightsaber_routes import lightsaber
from .master_routes import master
from .padawan_routes import padawan
from .species_routes import species
from .temple_routes import temple